spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ddns.webbershaw.fun:3306/wizard
    username: root
    password: Yy336699
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      pool-prepared-statements: true
mybatis:
  type-aliases-package: edu.hunau.dao
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



