
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wizard
    username: root
    password: Yy336699
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      pool-prepared-statements: true
  servlet:
    # 上传限定参数
    multipart:
      # 是否启用分段上传支持
      enabled: true
      # 最大请求大小
      max-request-size: 60MB
      # 最大文件的大小
      max-file-size: 50MB
      #上传文件的中间位置
#      location: /User/webbershaw/temp

  mail:
    host: smtp.exmail.qq.com
    username: wenboxiao@stu.hunau.edu.cn
    password: Xiaoge0225
    default-encoding: utf-8
mybatis:
  type-aliases-package: edu.hunau.dao
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 443







  # yml 配置如下
  ssl:
    key-store: classpath:www.webbershaw.fun.jks
    key-store-password: f6wg4y97b27
    key-store-type: JKS
azureblob:
  defaultEndpointsProtocol: https
  blobEndpoint: https://q7fefidjmr6e6vpnsa.blob.core.windows.net/
  queueEndpoint: https://q7fefidjmr6e6vpnsa.queue.core.windows.net/
  tableEndpoint: https://q7fefidjmr6e6vpnsa.table.core.windows.net/
  accountName: q7fefidjmr6e6vpnsa
  accountKey: HyowlZ1QdbHEO6MXxUp/7JbKwfEsgjK63dVnxaLUlgMwk7xn1TZDWdhfDEWdaXbgZYJDpCRFvUhx+AStwHRUvA==








